### PR TITLE
explicit endorsement values and refval values

### LINKED ISSUE #53: granularity and isolation
While working on the PSA profile, one thing that doesn't feel right is that when extending ref-vals / endorsements values, one ends up extending the _whole_ ref-val/endorsement map rather than just the element value -- which would seem to be the right granularity.  Now: `element-value` does not have an extension point, but even it had one, extending `element-value` with new endorsements types would have a polluting effect in that the endorsement-specific extensions would automatically percolate into the ref-val space and viceversa.  Which makes me wonder whether we got the type system slightly wrong here?  Wouldn't it be better instead of a shared `element-value` to have separate (and extensible) `endorsement-value` and `ref-val-value` inside the endorsement and ref-val maps respectively? ISTM that this approach would give us the granularity and isolation which the current type system lacks.

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fixes #53

### CODE REVIEW

**Comment by nedmsmith** [comment]
It seems there are overlapping changes between #53 and #56 where element-value-map is changing to element-value-group, but #53 is still relying on element-value-map but #56 doesn't also update the instance maps to incorporate the change to element-value-group. Possibly, I'm not following fully the proposed changes so maybe these could be merged into a single PR?

**Comment by thomas-fossati** [comment]
We discussed whether to merge the two PRs into one (this one) or not, and decided that it may be clearer to keep the two separate  for now.  You should try and look at each PR in isolation, if it's not too confusing :-)

**Comment by nedmsmith** [comment]
That is what was confusing me. Why wouldn’t the ref-instance-claim-map use element-value-group?

From: Thomas Fossati ***@***.***>
Reply-To: ietf-rats/ietf-corim-cddl ***@***.***>
Date: Tuesday, May 4, 2021 at 10:32 AM
To: ietf-rats/ietf-corim-cddl ***@***.***>
Cc: "Smith, Ned" ***@***.***>, Review requested ***@***.***>
Subject: Re: [ietf-rats/ietf-corim-cddl] explicit endorsement values and refval values (#56)


We discussed whether to merge the two PRs into one (this one) or not, and decided that it may be clearer to keep the two separate for now. You should try and look at each PR in isolation, if it's not too confusing :-)

**Comment by thomas-fossati** [comment]
> That is what was confusing me. Why wouldn’t the ref-instance-claim-map use element-value-group?

Yes, you are right, that should be the case.  For the time being -- until we put the two together -- you need to pretend to see the group there instead of the map :)

**Comment by yogeshbdeshpande** [comment]
As discussed earlier, please review explicit endorsement values and refval values (#56), change and then I will realign the ref-instance-claim-map and instance-endorsement maps
Accordingly.

Keeping it two separate is done as Thomas raised the point as part of PSA Endorsements.

Once we review that, I will rebase my changes on Issue #51 fix to address your point above.

Regards,
Yogesh

**Review by nedmsmith — APPROVED** [review]

**Pull request merged**
