### PR TITLE
align xcorim layout with recent changes to corim

### LINKED ISSUE #135: Tidy up naming to avoid confusion - Xcorim unprotected-signed
Xcorim schema follows a similar convention 'unprotected-signed-xcorim-header-map' which should be 'unprotected-xcorim-header-map'

### LINKED ISSUE #136: Xcorim entities and roles
The Xcorim structure is similar to the CoRIM structure having a signer in the signed-xcorim and a creator in the unsigned xcorim. Should the xcorim schema be adjusted similarly to PR#130?

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fixes #136, Fixes #135

### CODE REVIEW

**Review by nedmsmith — APPROVED** [review]

**Review by yogeshbdeshpande — APPROVED** [review]

**Comment by nedmsmith** [comment]
`protected-signed-xcorim-header-map = { `

Should this be changed to:
`protected-xcorim-header-map = {`

**Comment by yogeshbdeshpande** [comment]
> `protected-signed-xcorim-header-map = { `
> 
> Should this be changed to: `protected-xcorim-header-map = {`

No, the existing name is correct. This protected section is part of xcorim signature.

**Comment by thomas-fossati** [comment]
> > `protected-signed-xcorim-header-map = { `
> > Should this be changed to: `protected-xcorim-header-map = {`
> 
> No, the existing name is correct. This protected section is part of xcorim signature.

true, though TBH a bit pleonastic...

**Comment by yogeshbdeshpande** [comment]
> pleonastic

No, its not, in fact it is necessary, given the fact that part of the structure elements (fields) are not part of signature and part does have signature over them!

**Comment by thomas-fossati** [comment]
> > pleonastic
> 
> No, its not, in fact it is necessary, given the fact that part of the structure elements (fields) are not part of signature and part does have signature over them!

"protected" and "signed" are nearly synonyms in this case...  anyway, mine was just a fly-by note, I have no stakes in this matter :-)

**Review by nedmsmith — APPROVED** [review]

**Pull request merged**
